### ISSUE TITLE
Broken link from facebook post

### ISSUE THREAD

**Issue by hector-meza** [IBM/developer_es#1]
https://developer.ibm.com/es/events/build-smart-on-kubernetes-red-hat-openshift/?social_post=3471837874&linkId=93010618

**Comment by gabbyret** [comment]
@hector-meza Hector, te paso el link correcto y gracias por avisarnos.
https://developer.ibm.com/es/events/bsok-red-hat-openshift-b-sico-latam-espa-a-1er-sesi-n/
