### ISSUE TITLE
Error en Link de Containers y Despliegue de una Imagen Docker de tomcat

### ISSUE THREAD

**Issue by ismaeloe** [IBM/developer_es#2]
Cuando doy Click en Despliegue de una Imagen Docker de tomcat
Regresa el mensaje = Lo sentimos, pero no podemos encontrar la página que está buscando

**Comment by Ketring-public** [comment]
@gabbyret has this been resolved?

**Comment by gabbyret** [comment]
@Ketring-public Not yet Leah, I hadn´t seen it.

@ismaeloe Ismael, perdon en la demora en responderte! Podrías indicarme que página estabas viendo? Gracias
