### ISSUE TITLE
Liga rota

### ISSUE THREAD

**Issue by gengube** [IBM/developer_es#3]
Este archivo skill-Clima-json no lo deja descargar https://developer.ibm.com/es/skill-Clima.json, tampoco en la anterior liga https://developer.ibm.com/es/technologies/artificial-intelligence/skill-Clima.json, podrían proporcionármelo ya que lo necesito para una práctica que están elaborando mis alumnos, saludos.

**Comment by gabbyret** [comment]
@gengube Hola! Solo para confirmar es de este tutorial no? https://developer.ibm.com/es/tutorials/cloud-functions/

**Comment by gengube** [comment]
Así es, saludos.

**Comment by BrunoVicario** [comment]
@gengube te dejo el link que me pasó la autora del tutorial, ahí podés encontrar ese archivo. Voy a actualizar el tutorial original, pero mientras podés bajarlo desde acá https://github.ibm.com/belcecilia/IBMCloudFunctions
Gracias por avisar!

**Comment by Ketring-public** [comment]
@gabbyret can this issue be closed?
