### ISSUE TITLE
Favor enorme: A un artículo en IBM Developers le faltan las imagenes.

### ISSUE THREAD

**Issue by aquilesloranca** [IBM/developer_es#4]
¡Buenas tardes!

Mi nombre es Aquiles Loranca, y soy el autor del artículo:

**Instalación y prueba básica de conexión a una instancia de Informix a través de un driver JDBC de IBM – (Parte 1)**
https://developer.ibm.com/es/devpractices/software-development/tutorials/jdbc-informix/

Y observo que faltan las imagenes ilustrativas del mismo.

¿Pudieran por favor ayudarme a actualizar el mismo?

De antemano mil gracias.

**Comment by gabbyret** [comment]
Hola @aquilesloranca si, claro!  Te contacto por Slack! 
Saludos
Gaby
