### ISSUE TITLE
Servidor IBM System x3200

### ISSUE THREAD

**Issue by ccollado0307** [IBM/developer_es#5]
Buen Dia!
Tengo un Servidor IBM System x3200.
Necesito instalar Windows Server 2016. 
El tema es que este servidor no bootea desde pendrive y en CD no lo puedo grabar porque la imagen ocupa mas de 4GB.
No puedo actualizar la BIOS porque necesito un pendrive de 1 GB que no poseo. 
Necesito saber si existe alguna forma de resolver este inconveniente.

**Comment by Ketring-public** [comment]
@gabbyret can you address this issue as appropriate?

**Comment by gabbyret** [comment]
@ccollado0307 Hola! Entiendo esos equipos hoy los vende Lenovo. Recomiendo que te contactes con ellos en tu país. https://support.lenovo.com/ec/es/solutions/HT113160 
Saludos
